# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{traits}
  s.version = "0.2.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["dieinzige"]
  s.date = %q{2010-11-08}
  s.description = %q{Watch description}
  s.email = %q{dieinzige@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/traits.rb",
     "lib/traits/controller.rb",
     "lib/traits/controller/actions.rb",
     "lib/traits/controller/actions/create.rb",
     "lib/traits/controller/actions/destroy.rb",
     "lib/traits/controller/actions/edit.rb",
     "lib/traits/controller/actions/index.rb",
     "lib/traits/controller/actions/new.rb",
     "lib/traits/controller/actions/show.rb",
     "lib/traits/controller/actions/update.rb",
     "lib/traits/controller/authorization.rb",
     "lib/traits/controller/authorizations/authlogic.rb",
     "lib/traits/controller/resource.rb",
     "lib/traits/model.rb",
     "test/helper.rb",
     "test/test_traits.rb",
     "traits.gemspec"
  ]
  s.homepage = %q{http://github.com/dieinzige/traits}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Common usage patters, at my rails stack}
  s.test_files = [
    "test/helper.rb",
     "test/test_traits.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

